{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/25491",
  "id": 1330976100,
  "node_id": "I_kwDOAOvK985PVRVk",
  "number": 25491,
  "title": "Geth not start bind: address already in use",
  "user": {
    "login": "Piradoxlanieve",
    "id": 10765838,
    "node_id": "MDQ6VXNlcjEwNzY1ODM4",
    "avatar_url": "https://avatars.githubusercontent.com/u/10765838?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Piradoxlanieve",
    "html_url": "https://github.com/Piradoxlanieve",
    "followers_url": "https://api.github.com/users/Piradoxlanieve/followers",
    "following_url": "https://api.github.com/users/Piradoxlanieve/following{/other_user}",
    "gists_url": "https://api.github.com/users/Piradoxlanieve/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Piradoxlanieve/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Piradoxlanieve/subscriptions",
    "organizations_url": "https://api.github.com/users/Piradoxlanieve/orgs",
    "repos_url": "https://api.github.com/users/Piradoxlanieve/repos",
    "events_url": "https://api.github.com/users/Piradoxlanieve/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Piradoxlanieve/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 72233650,
      "node_id": "MDU6TGFiZWw3MjIzMzY1MA==",
      "url": "https://api.github.com/repos/ethereum/go-ethereum/labels/type:bug",
      "name": "type:bug",
      "color": "FF5E5E",
      "default": false,
      "description": ""
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2022-08-07T10:30:42Z",
  "updated_at": "2022-08-07T17:09:38Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "#### System information\r\n\r\nGeth version: `Geth/v1.10.21-stable-67109427/linux-amd64/go1.18.4`\r\nOS & Version: Ubuntu 20.04.4\r\n\r\nHi. I had my geth node working perfectly, I restarted the pc and now I have this error\r\n\r\n```\r\nago 07 12:09:46 nodoeth geth[11482]: WARN [08-07|12:09:46.352] IPC opening failed url=/mnt/ssd/geth.ipc error=\"listen unix /mnt/ssd/geth.ipc: bind: address already in use\"\r\n\r\nago 07 12:09:47 nodoeth geth[11482]: Fatal: Error starting protocol stack: listen unix /mnt/ssd/geth.ipc: bind: address already in use\r\n\r\nago 07 12:09:47 nodoeth systemd[1]: eth1.service: Main process exited, code=exited, status=1/FAILURE\r\n\r\nago 07 12:09:47 nodoeth systemd[1]: eth1.service: Failed with result 'exit-code'.\r\n\r\nago 07 12:09:48 nodoeth systemd[1]: Stopped geth execution client service.\r\n\r\n```\r\n```\r\nroot@nodoeth:/mnt/ssd# ps ax | grep geth\r\n\r\n11893 pts/2 S+ 0:00 grep --color=auto geth\r\n\r\nroot@nodoeth:/mnt/ssd#\r\n```\r\n\r\nthe only solution I find is to change the geth directory and re-synchronize or also --ipcdisable but I don't know what affects this flag. Any ideas. I've been several hours and I don't see what address is using geth.ipc\r\n\r\nSorry my bad english.",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
[
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1207448259",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/25491#issuecomment-1207448259",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491",
    "id": 1207448259,
    "node_id": "IC_kwDOAOvK985H-DLD",
    "user": {
      "login": "ndevmetax",
      "id": 110781644,
      "node_id": "U_kgDOBppkzA",
      "avatar_url": "https://avatars.githubusercontent.com/u/110781644?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ndevmetax",
      "html_url": "https://github.com/ndevmetax",
      "followers_url": "https://api.github.com/users/ndevmetax/followers",
      "following_url": "https://api.github.com/users/ndevmetax/following{/other_user}",
      "gists_url": "https://api.github.com/users/ndevmetax/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ndevmetax/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ndevmetax/subscriptions",
      "organizations_url": "https://api.github.com/users/ndevmetax/orgs",
      "repos_url": "https://api.github.com/users/ndevmetax/repos",
      "events_url": "https://api.github.com/users/ndevmetax/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ndevmetax/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-08-07T17:09:38Z",
    "updated_at": "2022-08-07T17:09:38Z",
    "author_association": "NONE",
    "body": "> #### System information\r\n> Geth version: `Geth/v1.10.21-stable-67109427/linux-amd64/go1.18.4` OS & Version: Ubuntu 20.04.4\r\n> \r\n> Hi. I had my geth node working perfectly, I restarted the pc and now I have this error\r\n> \r\n> ```\r\n> ago 07 12:09:46 nodoeth geth[11482]: WARN [08-07|12:09:46.352] IPC opening failed url=/mnt/ssd/geth.ipc error=\"listen unix /mnt/ssd/geth.ipc: bind: address already in use\"\r\n> \r\n> ago 07 12:09:47 nodoeth geth[11482]: Fatal: Error starting protocol stack: listen unix /mnt/ssd/geth.ipc: bind: address already in use\r\n> \r\n> ago 07 12:09:47 nodoeth systemd[1]: eth1.service: Main process exited, code=exited, status=1/FAILURE\r\n> \r\n> ago 07 12:09:47 nodoeth systemd[1]: eth1.service: Failed with result 'exit-code'.\r\n> \r\n> ago 07 12:09:48 nodoeth systemd[1]: Stopped geth execution client service.\r\n> ```\r\n> \r\n> ```\r\n> root@nodoeth:/mnt/ssd# ps ax | grep geth\r\n> \r\n> 11893 pts/2 S+ 0:00 grep --color=auto geth\r\n> \r\n> root@nodoeth:/mnt/ssd#\r\n> ```\r\n> \r\n> the only solution I find is to change the geth directory and re-synchronize or also --ipcdisable but I don't know what affects this flag. Any ideas. I've been several hours and I don't see what address is using geth.ipc\r\n> \r\n> Sorry my bad english.\r\n\r\n\r\nI had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1207448259/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
