{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25910",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25910/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25910/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25910/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/25910",
  "id": 1393005850,
  "node_id": "I_kwDOAOvK985TB5Ua",
  "number": 25910,
  "title": "Inconsistency with stack depth check in js-tracer",
  "user": {
    "login": "cattingcat",
    "id": 5341725,
    "node_id": "MDQ6VXNlcjUzNDE3MjU=",
    "avatar_url": "https://avatars.githubusercontent.com/u/5341725?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/cattingcat",
    "html_url": "https://github.com/cattingcat",
    "followers_url": "https://api.github.com/users/cattingcat/followers",
    "following_url": "https://api.github.com/users/cattingcat/following{/other_user}",
    "gists_url": "https://api.github.com/users/cattingcat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/cattingcat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/cattingcat/subscriptions",
    "organizations_url": "https://api.github.com/users/cattingcat/orgs",
    "repos_url": "https://api.github.com/users/cattingcat/repos",
    "events_url": "https://api.github.com/users/cattingcat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/cattingcat/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 268304226,
      "node_id": "MDU6TGFiZWwyNjgzMDQyMjY=",
      "url": "https://api.github.com/repos/ethereum/go-ethereum/labels/type:docs",
      "name": "type:docs",
      "color": "fef2c0",
      "default": false,
      "description": null
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2022-09-30T20:45:08Z",
  "updated_at": "2022-10-01T03:29:39Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "I found inconsistency with error messages about stack underflow. For example:\r\n\r\nSome commands returns error with log.getError()\r\n\r\ncode:\r\n```\r\nvar err = log.getError();\r\n    if (err) {\r\n      this.callContractEnter = false;\r\n      this.debug.push([log.getPC(), log.op.toString(), log.getDepth(), this.callstack.length, 'err step', err]);\r\n      ...\r\n```\r\n\r\n```\r\nArray(6) [0, LOG4, 3, 3, err step, stack underflow (0 <=> 6)]\r\nArray(6) [0, AND, 3, 3, err step, stack underflow (0 <=> 2)]\r\nArray(6) [0, DUP9, 3, 3, err step, stack underflow (0 <=> 9)]\r\n```\r\n\r\n\r\nAnd REVERT called in both places in step function with empty stack (in my case) so I can't get stack params because it breaks my traces\r\nand after that it is processed inside fault function\r\n\r\nTransaction with lots of stack issues: 0x93985273e6b0a0744a09261cd75fa5abd7ebacb9406ccff25a89463a303f4cda (mainnet)\r\n\r\nIs it correct behaviour?",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25910/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25910/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
[
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1264221658",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/25910#issuecomment-1264221658",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25910",
    "id": 1264221658,
    "node_id": "IC_kwDOAOvK985LWn3a",
    "user": {
      "login": "sadozh",
      "id": 95658062,
      "node_id": "U_kgDOBbOgTg",
      "avatar_url": "https://avatars.githubusercontent.com/u/95658062?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sadozh",
      "html_url": "https://github.com/sadozh",
      "followers_url": "https://api.github.com/users/sadozh/followers",
      "following_url": "https://api.github.com/users/sadozh/following{/other_user}",
      "gists_url": "https://api.github.com/users/sadozh/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sadozh/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sadozh/subscriptions",
      "organizations_url": "https://api.github.com/users/sadozh/orgs",
      "repos_url": "https://api.github.com/users/sadozh/repos",
      "events_url": "https://api.github.com/users/sadozh/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sadozh/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-10-01T03:29:38Z",
    "updated_at": "2022-10-01T03:29:38Z",
    "author_association": "NONE",
    "body": "And REVERT called in both places in step function with empty stack (in my case) so I can't get stack params because it breaks my traces\nand after that it is processed inside fault function\n\nTransaction with lots of stack issues: 0x93985273e6b0a0744a09261cd75fa5abd7ebacb9406ccff25a89463a303f4cda (mainnet)\n\nIs it correct behaviour?",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1264221658/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
